CREATE TABLE TBL_AUTHENTICATION (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name TEXT,
    photo_url TEXT,
    phone_number TEXT UNIQUE,
    email_verified BOOLEAN DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TBL_LOGS (
    log_id INTEGER PRIMARY KEY AUTOINCREMENT,
    date DATE NOT NULL,
    time TIME NOT NULL,
    average_delta REAL NOT NULL,
    PerCompleted REAL NOT NULL
);

CREATE TABLE TBL_PARAMETER 
(
    IPARAMID INTEGER PRIMARY KEY,
    SNAME TEXT NOT NULL,
    SDESC TEXT,
    SUNIT TEXT,
    RREF REAL,          -- Represents FLOAT
    RMIN REAL,          -- Represents FLOAT
    RMAX REAL,          -- Represents FLOAT
    RDEF REAL,          -- Represents FLOAT
    DTICREATED DATE, -- Represents TIMESTAMP
    DTIMODIFIED DATE, -- Represents TIMESTAMP
    REPLASTUSER TEXT,
    REPUNIQUE TEXT,
    UNIQUE (SNAME)
);

CREATE TABLE TBL_POST 
(
    IPOSTID INTEGER PRIMARY KEY,
    SNAME TEXT NOT NULL,
    SDESC TEXT,
    DTICREATED DATE, -- Represents TIMESTAMP
    DTIMODIFIED DATE, -- Represents TIMESTAMP
    REPLASTUSER TEXT,
    UNIQUE (SNAME)
);

CREATE TABLE TBL_VARIABLE 
(
    IVARID INTEGER NOT NULL,
    IPARAMID INTEGER NOT NULL,
    IPOSTID INTEGER NOT NULL,
    SSOURCENAME TEXT,          -- Changed from VARCHAR to TEXT
    DTICREATED  DATE,
    DTIMODIFIED DATE,
    REPLASTUSER TEXT,          -- Changed from VARCHAR to TEXT
    REPUNIQUE TEXT,            -- Changed from VARCHAR to TEXT
    CONSTRAINT CONSTRAINT_VARIABLE UNIQUE (IPARAMID, IPOSTID) ON CONFLICT REPLACE,
    PRIMARY KEY (IVARID),
    FOREIGN KEY (IPARAMID) REFERENCES TBL_PARAMETER(IPARAMID) ON DELETE CASCADE,
    FOREIGN KEY (IPOSTID) REFERENCES TBL_POST(IPOSTID) ON DELETE CASCADE
);

CREATE TABLE TBL_DATAINBOX (
    DTITIMESTAMP        DATE NOT NULL,
    ISITEID           INTEGER NOT NULL,
    IOBJECTID         INTEGER NOT NULL,
    IUSERID            INTEGER NOT NULL,
    RVALUE            REAL,
    SVALUE            TEXT DEFAULT NULL,
    JSVALUE           TEXT DEFAULT NULL,
    UVALUE            INTEGER DEFAULT NULL,
    IVALUE            INTEGER DEFAULT NULL,
    UNIQUE(DTITIMESTAMP, ISITEID, IOBJECTID) ON CONFLICT REPLACE,
    FOREIGN KEY (ISITEID) REFERENCES TBL_SITE(ISITEID)
);

CREATE TABLE TBL_SITE
(
    ISITEID INTEGER PRIMARY KEY,
    SLANGUAGE TEXT,
    SFEDERAL_ID TEXT,
    JSCONTACTDETAILS TEXT,
    SSTEPNAME TEXT,
    SSITENAME TEXT,
    JSBASICINFO TEXT,
    JSSPECIFIC_CTES TEXT,
    JSDOCLIST TEXT,
    JSMAILADDRESSLIST TEXT,
    JSNOTES TEXT,
    SMEMONOTE TEXT
);





